<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="logo">
      <a href="#"><img src="theme/images/logo-a.png" alt=""></a>
    </div>
    <div class="copy">
      © 2017 Wee Casa
    </div>
    <div class="nav">
      <ul>
        <li><a href="#">START YOUR OWN WEE CASA</a></li>
        <li><a href="#">LIST YOUR TINY HOUSE</a></li>
        <li><a href="#">PARTNERS</a></li>
        <li><a href="#">BOOK A TOUR</a></li>
        <li class="mobile-only"><a data-toggle="modal" data-target="#popup-sign-up" href="#">newsletter signup</a></li>
      </ul>
    </div>
    <div class="social">
      <ul>
        <li class="social-1"><a href="#"></a></li>
        <li class="social-2"><a href="#"></a></li>
        <li class="social-3"><a href="#"></a></li>
        <li class="social-4"><a href="#"></a></li>
      </ul>
    </div>
    <div class="reviews">
      <div class="left-part">
        <div class="b-tripadvisor">
          <div class="logo">
            <div class="img">
              <img src="theme/images/tmp/trip-logo.png" alt=""/>
            </div>
            <div class="count">
              <span class="rating-wrap">
                <span class="rating rating-9">
                  <span></span>
                  <span></span>
                  <span></span>
                  <span></span>
                  <span></span>
                </span>
              </span>
              <span class="count-wrap">
                <span>13</span>
               Reviews
              </span>
            </div>
          </div>
          <div class="content-wrap">
            <div class="inner-wrap">
              <div class="previews-wrap">
                <div>
                    <div class="preview">
                        <p>What an awesome way to try out living Tiny. Very Clean and well maintained. The location is awesome...about 30 minutes to Rocky Mountain National Park</p>
                      <a class="read-more" href="#">Read More</a>
                    </div>
                    <div class="preview">
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet cupiditate debitis ducimus
                        enim ex expedita explicabo hic, incidunt ipsum laborum libero maxime nam nesciunt numquam odio
                        ratione reiciendis tenetur?
                      </p>
                    </div>
                    <div class="preview">
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet cupiditate debitis ducimus
                        enim ex expedita explicabo hic, incidunt ipsum laborum libero maxime nam nesciunt numquam odio
                        ratione reiciendis tenetur?
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias amet cupiditate debitis ducimus
                        enim ex expedita explicabo hic, incidunt ipsum laborum libero maxime nam nesciunt numquam odio
                        ratione reiciendis tenetur?</p>
                      <a class="read-more" href="#">Read More</a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="right-part">
        <div class="bg">
          <a href="#">
            <img src="theme/images/tmp/tmp-img-ico-1.png" alt=""/>
          </a>
        </div>
      </div>
    </div>
  </div>
</footer>
<div class="b-modal modal fade" id="popup-sign-up" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" style="background-image: url('theme/images/tmp/section-newsletter.jpg')">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
      </div>
      <div class="modal-body">
        <h2>CHECK OUT OUR NEWSLETTER</h2>
        <div class="form form-sign-up">
          <div class="row">
            <div class="form-item form-type-text col-sm-6">
              <input type="text" class="form-text" placeholder="First Name">
            </div>
            <div class="form-item form-type-text col-sm-6">
              <input type="text" class="form-text" placeholder="Last Name">
            </div>
          </div>
          <div class="row">
            <div class="form-item form-type-text col-sm-6">
              <input type="text" class="form-text" placeholder="Email Address">
            </div>
            <div class="form-item form-type-text col-sm-6">
              <input type="text" class="form-text" placeholder="Confirm Email Address">
            </div>
          </div>
          <div class="form-actions">
            <div class="form-submit-wrap">
              <input type="submit" class="form-submit" value="SIGN UP">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>