<header id="site-header" class="site-header">
  <div class="container">
    <div class="header-inner">
      <nav class="navigation">
        <a href="#" class="btn-nav"></a>
        <div class="content">
          <ul class="menu">
            <li class="logo-top">
              <a href="#">
             <span class="logo-wrapper">
               <img src="theme/images/logo.png" alt=""/>
             </span>
              </a>
            </li>
            <li class="expanded"><a href="#">ABOUT YOUR STAY</a>
              <ul class="menu">
                <li><a class="active" href="#">Amentities</a></li>
                <li class="expanded"><a href="#">EventsGroups</a>
                    <ul class="menu">
                      <li class="first last leaf">
                        <a href="#">WeeCasa Events</a>
                      </li>
                    </ul>
                </li>
                <li><a href="#">GuestPoliciesFAQ</a></li>
                <li><span title="" class="nolink">More Locations Coming Soon</span></li>
              </ul>
            </li>
            <li class="expanded"><a href="#">LOCATIONS</a>
              <ul class="menu">
                <li><a href="#">CasaGallery</a></li>
                <li><a href="#">Thingstodo</a></li>
              </ul>
            </li>
            <li><a href="#">CONTACT US</a></li>
          </ul>
        </div>
      </nav>
      <div class="btn-wrap">
        <a class="btn" href="/weecasa/slice/public/Home2.php">
          BOOK YOUR STAY
        </a>
      </div>
      <div class="link-wrap">
        <div class="link-inner">
          <a href="tel:720.460.0239">
          <span class="ico ss-icon ss-social-regular ss-phone">
          </span>
            720.460.0239
          </a>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="sticky-btn">
  <div class="container">
    <div class="inner">
        <a class="btn style-a" href="#">
          CHECK AVAILABILITY
        </a>
    </div>
  </div>
</div>


