<section class="section section-newsletter">
  <div class="bg-wrap">
    <div class="bg" style="background-image: url('theme/images/tmp/section-newsletter.jpg')">
    </div>
  </div>
  <div class="container">
    <div class="inner-wrap">
      <div class="left-part">
        <h2>CHECK<br>
          OUT<br>
          OUR<br>
          NEWSLETTER</h2>
      </div>
      <div class="right-part">
        <div class="form form-sign-up">
          <div class="row">
            <div class="form-item form-type-text col-sm-6">
              <input type="text" class="form-text" placeholder="First Name">
            </div>
            <div class="form-item form-type-text col-sm-6">
              <input type="text" class="form-text" placeholder="Last Name">
            </div>
          </div>
          <div class="row">
            <div class="form-item form-type-text col-sm-6">
              <input type="text" class="form-text" placeholder="Email Address">
            </div>
            <div class="form-item form-type-text col-sm-6">
              <input type="text" class="form-text" placeholder="Confirm Email Address">
            </div>
          </div>
          <div class="form-actions">
            <div class="form-submit-wrap">
              <input type="submit" class="form-submit" value="SIGN UP">
              <div class="ajax-progress ajax-progress-throbber"><div class="throbber">&nbsp;</div></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>