<div class="item">
  <div class="anim-wrap">
    <div class="tilter__figure">
      <a href="#">
        <img src="<?php print $element[1]; ?>" alt=""/>
        <span class="tilter__deco--lines">
          <span class="title-wrap">
            <span class="sub-title">
              THE
            </span>
            <span class="title"><?php print $element[0]; ?> </span>
          </span>
        </span>
        <span class="tilter__deco--overlay">
        </span>
        <span class="tilter__caption">
          <span class="info">
            <span class="inner-wrap">
              <span class="sleeps">
                SLEEPS
                <span class="amount"><?php print $element[2]; ?></span>
              </span>
              <span class="more">
                MORE INFO
              </span>
           </span>
          </span>
        </span>
      </a>
    </div>
  </div>
</div>